[xdebug]
; Xdebug configuration (overridden by XDEBUG_MODE env var)
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.discover_client_host=1
xdebug.client_host = host.docker.internal
xdebug.client_port = ${XDEBUG_PORT}
xdebug.log = /tmp/xdebug.log
xdebug.max_nesting_level = 512
