shared_buffers 128MB
effective_cache_size 512MB
work_mem 16MB
maintenance_work_mem 64MB
max_connections 100
random_page_cost 1.1
wal_buffers 16MB
log_slow_statements on
log_min_duration_statement = 1000
